# Generated by Django 4.2.3 on 2023-11-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_customuser_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usuario',
            new_name='author',
        ),
    ]
