# Generated by Django 4.2.3 on 2023-11-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0008_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
    ]
